
homeassistant:
  name: Crochon
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  packages: !include_dir_named packages
  external_url: !secret external-url
  internal_url: !secret internal-url
# country: FR

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# configuration des log
logger:
  default: info
  logs:
# log level for HA core
    homeassistant.core: fatal

# log level for MQTT integration
    homeassistant.components.mqtt: warning

# log level for all python scripts
    homeassistant.components.python_script: warning

# individual log level for this python script
    homeassistant.components.python_script.my_new_script.py: warning

# log level for SmartThings lights
    homeassistant.components.smartthings.light: warning
    
# log level for a custom component
    #custom_components.my_integration: debug
    custom_components.pool_pump: debug
    
# log level for the `aiohttp` Python package
    aiohttp: error

# log level for both 'glances_api' and 'glances' integration
    homeassistant.components.glances: fatal
    glances_api: fatal
    
#base de données
    homeassistant.components.recorder: warning
    
# RFXCOM
    rfxtrx: warning

# Modbus
    homeassistant.components.modbus: warning
    pymodbus.client: warning

#AutomMower
    custom_components.husqvarna_automower: warning
    custom_components.husqvarna_automower.vacuum: warning
    custom_components.husqvarna_automower.config_flow: warning
    aioautomower: warning

# Text to speech
tts:
  - platform: google_translate

# Inclusion des themes
frontend:
  themes: !include_dir_merge_named themes/

# Cartes
lovelace:
#  mode: yaml
#  resources: !include www/custom-lovelace/resources.yaml

#  - url: /local/meteofrance/meteofrance-raininhourforecast.js
#    type: module

#lovelace_gen:

# Inclusion groupes/automatismes/script/scene
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#hacs:
#  token: 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

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.105
    - 192.168.0.153

#glances:
#  - host: 192.168.0.37

rfxtrx:
 device: //dev/serial/by-id/usb-RFXCOM_RFXtrx433_A128N1JF-if00-port0
#  device: /dev/ttyUSB0

# Valide l'enregistrement dans les bases de données
recorder:
  db_url: !secret db_mysql
  auto_purge: true
  commit_interval: 15
  purge_keep_days: 7
  include:
    domains:
      - binary_sensor
      - input_boolean
      - input_datetime
      - input_number
      - input_select
      - sensor
      - switch
      - light
      - utility_meter
      - vacuum
      - sun
      - device_tracker
      - weather
      - group   
      - person
      
  exclude:
    domains:
      - camera
      - zone
      - automation
      - cover
      - script
      - pool_pump
      - alarm_control_panel
      - climate
      - persistent_notification


# base influxdb
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant2
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - binary_sensor
      - input_boolean
      - input_datetime
      - input_number
      - input_select
      - sensor
      - switch
      - light
      - utility_meter
      - vacuum
      - sun
  exclude:
    domains:
      - camera
      - zone
      - automation
      - weather
      - cover
      - group
      - script
      - pool_pump
      - device_tracker
      - alarm_control_panel
      - climate
      - persistent_notification
      - person




# Notification dans Telegram 
telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret id_telegram_remy ## remy
      
notify:
  - name: Telegram
    platform: telegram
    chat_id: !secret id_telegram_remy

  - platform: pushbullet
    api_key: !secret pushbullet_api_key
    name: pushbullet

# Notification dans les fichiers
  - name: log_energy
    platform: file
    filename: conso_energy.csv
    timestamp: True

  - name: log_piscine
    platform: file
    filename: conso_piscine.csv
    timestamp: True

livebox:
  host: 192.168.0.1
  username: !secret user_livebox
  password: !secret mdp_livebox
  
#owntracks:
#  max_gps_accuracy: 200
#  waypoints: false
#  mqtt_topic: "owntracks/#"

python_script:

api:
    
alexa:
  smart_home:

shell_command:
  push_to_github: /config/gitpush.sh
  turn_off_remote_pc: "ssh -i /config/.ssh/id_rsa_homeassistant -o 'StrictHostKeyChecking=no' homeassistant@192.168.0.62 sudo reboot -h now"

sensor:
  - platform: zwift
    username: !secret my_zwift_username
    password: !secret my_zwift_password
#    players:
#      - !secret my_friends_zwift_player_id