---
# Light toggle button
# vars:
  # uid:
  # height:
  # text:
  # icon:
  # entity_id:
height: ${height}
id: button_${uid}
widgets:
  - label:
      text_font: $icon_font
      align: top_left
      id: icon_${uid}
      text: ${icon}
  - label:
      align: bottom_left
      id: label_${uid}
      text: ${text}
on_short_click:
    - homeassistant.action:
        action: light.toggle
        data:
          entity_id: ${entity_id}