globals:
  - id: table_puissance
    type: std::vector<std::pair<float, float>>
    restore_value: no
    initial_value: |-
      {{
        {0.000000,0.000000},
        {1.000000,0.000000},
        {2.000000,0.000000},
        {3.000000,0.000000},
        {4.000000,0.000000},
        {5.000000,0.000000},
        {6.000000,0.000000},
        {7.000000,0.000000},
        {8.000000,0.000000},
        {9.000000,0.000000},
        {10.000000,0.000000},
        {11.000000,0.000000},
        {12.000000,0.000000},
        {13.000000,0.000000},
        {14.000000,0.000000},
        {15.000000,0.000000},
        {16.000000,0.000000},
        {17.000000,0.000000},
        {18.000000,0.000000},
        {19.000000,0.000000},
        {20.000000,0.000000},
        {21.000000,0.000000},
        {22.000000,15.833049},
        {23.000000,25.982599},
        {24.000000,39.162422},
        {25.000000,54.734337},
        {26.000000,72.311447},
        {27.000000,92.974602},
        {28.000000,116.767052},
        {29.000000,145.161240},
        {30.000000,174.444473},
        {31.000000,208.626556},
        {32.000000,248.422882},
        {33.000000,288.993408},
        {34.000000,326.663391},
        {35.000000,371.590698},
        {36.000000,418.432220},
        {37.000000,476.680573},
        {38.000000,521.119507},
        {39.000000,571.505554},
        {40.000000,635.195129},
        {41.000000,691.521362},
        {42.000000,744.049927},
        {43.000000,816.032837},
        {44.000000,886.714478},
        {45.000000,962.887512},
        {46.000000,1020.908081},
        {47.000000,1098.667236},
        {48.000000,1157.698486},
        {49.000000,1232.563599},
        {50.000000,1298.973877},
        {51.000000,1384.243530},
        {52.000000,1454.860596},
        {53.000000,1527.758423},
        {54.000000,1579.458862},
        {55.000000,1656.447998},
        {56.000000,1721.349854},
        {57.000000,1807.784546},
        {58.000000,1838.029297},
        {59.000000,1919.867798},
        {60.000000,1972.704834},
        {61.000000,2017.672607},
        {62.000000,2024.030029},
        {63.000000,2135.362549},
        {64.000000,2177.277588},
        {65.000000,2252.621582},
        {66.000000,2276.711426},
        {67.000000,2352.344971},
        {68.000000,2402.805908},
        {69.000000,2457.209229},
        {70.000000,2478.059814},
        {71.000000,2570.659668},
        {72.000000,2593.945312},
        {73.000000,2651.697754},
        {74.000000,2677.511230},
        {75.000000,2717.262207},
        {76.000000,2744.101562},
        {77.000000,2811.325439},
        {78.000000,2811.325439},
        {79.000000,2897.020020},
        {80.000000,2956.733398},
        {81.000000,2956.733398},
        {82.000000,2994.181885},
        {83.000000,3072.917480},
        {84.000000,3072.917480},
        {85.000000,3101.125732},
        {86.000000,3101.125732},
        {87.000000,3105.535156},
        {88.000000,3157.621582},
        {89.000000,3160.813477},
        {90.000000,3160.813477},
        {91.000000,3160.813477},
        {92.000000,3160.813477},
        {93.000000,3160.813477},
        {94.000000,3160.813477},
        {95.000000,3160.813477},
        {96.000000,3160.813477},
        {97.000000,3160.813477},
        {98.000000,3160.813477},
        {99.000000,3160.813477},
        {100.000000,3160.813477}

      }}
