
ads1115:
  - address: 0x48

binary_sensor:
  # Etat pression filtre
  # Si pression superieure à p_Max alors = True
  - platform: analog_threshold
    name: "Etat_pression_Filtre"
    sensor_id: pression_filtre    
    id: _etat_pression_filtre
    threshold: ${pression_max} # Défini dans Substitution en bar
    on_press:
        - lambda: |-                
            std::string mess= "ESP178 Seuil Pression Filtre Atteint";
            id(_message_telegram)->execute(mess.c_str(),0); 
            id(_log_fichier)->execute(mess.c_str(), 0);                
    on_release: 
        - lambda: |-                
            std::string mess= "ESP178 Pression filtre OK";
            id(_message_telegram)->execute(mess.c_str(),0);   
            id(_log_fichier)->execute(mess.c_str(), 0);
sensor:
    # Mesure de la pression filtre Entrée ANA 3
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 6.144
    name: "Pression_filtre"
    update_interval: 10s
    unit_of_measurement: "bar"
    device_class: pressure
    state_class: "measurement"
    id: pression_filtre
    filters:
#    - calibrate_linear:
#        - 0.561 -> 0.0
#        - 2.213 -> 0.81
    # moyenne sur 30 mn + affichage toutes les 2 mn
    - sliding_window_moving_average:
        window_size: 30
        send_every: 2
        send_first_at: 1
    on_value:        
        - lambda: |-
            ESP_LOGD("Pression", "Mesure brut: %.2f" " Mesure filtrée: %.2f", id(pression_filtre).raw_state,id(pression_filtre).state );